TRUNCATE TABLE IPT_BASIC_COLOR_C;

Insert into IPT_BASIC_COLOR_C
   (ID, REV_NBR, DESCRIPTION, DO_NOT_USE_IND, CHANGE_TYPE, CHANGE_USER_ID, CHANGE_TIMESTAMP, CONCEPT_REV_NBR, DCR_NBR, LEGACY_CHANGE_USER)
 Values
   (1, 1, 'black', '0', 'A', 1, TIMESTAMP '2002-12-14 15:56:32', 1, 21666, 'FDB');
Insert into IPT_BASIC_COLOR_C
   (ID, REV_NBR, DESCRIPTION, DO_NOT_USE_IND, CHANGE_TYPE, CHANGE_USER_ID, CHANGE_TIMESTAMP, CONCEPT_REV_NBR, DCR_NBR, LEGACY_CHANGE_USER)
 Values
   (2, 1, 'blue', '0', 'A', 1, TIMESTAMP '2002-12-14 15:56:32', 1, 21666, 'FDB');
Insert into IPT_BASIC_COLOR_C
   (ID, REV_NBR, DESCRIPTION, DO_NOT_USE_IND, CHANGE_TYPE, CHANGE_USER_ID, CHANGE_TIMESTAMP, CONCEPT_REV_NBR, DCR_NBR, LEGACY_CHANGE_USER)
 Values
   (19, 1, 'yellow', '0', 'A', 1, TIMESTAMP '2002-12-14 15:56:32', 1, 21666, 'FDB');
Insert into IPT_BASIC_COLOR_C
   (ID, REV_NBR, DESCRIPTION, DO_NOT_USE_IND, CHANGE_TYPE, CHANGE_USER_ID, CHANGE_TIMESTAMP, CONCEPT_REV_NBR, DCR_NBR, LEGACY_CHANGE_USER)
 Values
   (18, 1, 'white', '0', 'A', 1, TIMESTAMP '2002-12-14 15:56:32', 1, 21666, 'FDB');
Insert into IPT_BASIC_COLOR_C
   (ID, REV_NBR, DESCRIPTION, DO_NOT_USE_IND, CHANGE_TYPE, CHANGE_USER_ID, CHANGE_TIMESTAMP, CONCEPT_REV_NBR, DCR_NBR, LEGACY_CHANGE_USER)
 Values
   (17, 1, 'turquoise', '0', 'A', 1, TIMESTAMP '2002-12-14 15:56:32', 1, 21666, 'FDB');
Insert into IPT_BASIC_COLOR_C
   (ID, REV_NBR, DESCRIPTION, DO_NOT_USE_IND, CHANGE_TYPE, CHANGE_USER_ID, CHANGE_TIMESTAMP, CONCEPT_REV_NBR, DCR_NBR, LEGACY_CHANGE_USER)
 Values
   (16, 1, 'tan', '0', 'A', 1, TIMESTAMP '2002-12-14 15:56:32', 1, 21666, 'FDB');
Insert into IPT_BASIC_COLOR_C
   (ID, REV_NBR, DESCRIPTION, DO_NOT_USE_IND, CHANGE_TYPE, CHANGE_USER_ID, CHANGE_TIMESTAMP, CONCEPT_REV_NBR, DCR_NBR, LEGACY_CHANGE_USER)
 Values
   (15, 1, 'red', '0', 'A', 1, TIMESTAMP '2002-12-14 15:56:32', 1, 21666, 'FDB');
Insert into IPT_BASIC_COLOR_C
   (ID, REV_NBR, DESCRIPTION, DO_NOT_USE_IND, CHANGE_TYPE, CHANGE_USER_ID, CHANGE_TIMESTAMP, CONCEPT_REV_NBR, DCR_NBR, LEGACY_CHANGE_USER)
 Values
   (14, 1, 'purple', '0', 'A', 1, TIMESTAMP '2002-12-14 15:56:32', 1, 21666, 'FDB');
Insert into IPT_BASIC_COLOR_C
   (ID, REV_NBR, DESCRIPTION, DO_NOT_USE_IND, CHANGE_TYPE, CHANGE_USER_ID, CHANGE_TIMESTAMP, CONCEPT_REV_NBR, DCR_NBR, LEGACY_CHANGE_USER)
 Values
   (13, 1, 'pink', '0', 'A', 1, TIMESTAMP '2002-12-14 15:56:32', 1, 21666, 'FDB');
Insert into IPT_BASIC_COLOR_C
   (ID, REV_NBR, DESCRIPTION, DO_NOT_USE_IND, CHANGE_TYPE, CHANGE_USER_ID, CHANGE_TIMESTAMP, CONCEPT_REV_NBR, DCR_NBR, LEGACY_CHANGE_USER)
 Values
   (12, 1, 'peach', '0', 'A', 1, TIMESTAMP '2002-12-14 15:56:32', 1, 21666, 'FDB');
Insert into IPT_BASIC_COLOR_C
   (ID, REV_NBR, DESCRIPTION, DO_NOT_USE_IND, CHANGE_TYPE, CHANGE_USER_ID, CHANGE_TIMESTAMP, CONCEPT_REV_NBR, DCR_NBR, LEGACY_CHANGE_USER)
 Values
   (11, 1, 'orange', '0', 'A', 1, TIMESTAMP '2002-12-14 15:56:32', 1, 21666, 'FDB');
Insert into IPT_BASIC_COLOR_C
   (ID, REV_NBR, DESCRIPTION, DO_NOT_USE_IND, CHANGE_TYPE, CHANGE_USER_ID, CHANGE_TIMESTAMP, CONCEPT_REV_NBR, DCR_NBR, LEGACY_CHANGE_USER)
 Values
   (10, 1, 'off-white', '0', 'A', 1, TIMESTAMP '2002-12-14 15:56:32', 1, 21666, 'FDB');
Insert into IPT_BASIC_COLOR_C
   (ID, REV_NBR, DESCRIPTION, DO_NOT_USE_IND, CHANGE_TYPE, CHANGE_USER_ID, CHANGE_TIMESTAMP, CONCEPT_REV_NBR, DCR_NBR, LEGACY_CHANGE_USER)
 Values
   (9, 1, 'multi-colored', '0', 'A', 1, TIMESTAMP '2002-12-14 15:56:32', 1, 21666, 'FDB');
Insert into IPT_BASIC_COLOR_C
   (ID, REV_NBR, DESCRIPTION, DO_NOT_USE_IND, CHANGE_TYPE, CHANGE_USER_ID, CHANGE_TIMESTAMP, CONCEPT_REV_NBR, DCR_NBR, LEGACY_CHANGE_USER)
 Values
   (8, 1, 'lavender', '0', 'A', 1, TIMESTAMP '2002-12-14 15:56:32', 1, 21666, 'FDB');
Insert into IPT_BASIC_COLOR_C
   (ID, REV_NBR, DESCRIPTION, DO_NOT_USE_IND, CHANGE_TYPE, CHANGE_USER_ID, CHANGE_TIMESTAMP, CONCEPT_REV_NBR, DCR_NBR, LEGACY_CHANGE_USER)
 Values
   (7, 1, 'green', '0', 'A', 1, TIMESTAMP '2002-12-14 15:56:32', 1, 21666, 'FDB');
Insert into IPT_BASIC_COLOR_C
   (ID, REV_NBR, DESCRIPTION, DO_NOT_USE_IND, CHANGE_TYPE, CHANGE_USER_ID, CHANGE_TIMESTAMP, CONCEPT_REV_NBR, DCR_NBR, LEGACY_CHANGE_USER)
 Values
   (6, 1, 'gray', '0', 'A', 1, TIMESTAMP '2002-12-14 15:56:32', 1, 21666, 'FDB');
Insert into IPT_BASIC_COLOR_C
   (ID, REV_NBR, DESCRIPTION, DO_NOT_USE_IND, CHANGE_TYPE, CHANGE_USER_ID, CHANGE_TIMESTAMP, CONCEPT_REV_NBR, DCR_NBR, LEGACY_CHANGE_USER)
 Values
   (5, 1, 'gold', '0', 'A', 1, TIMESTAMP '2002-12-14 15:56:32', 1, 21666, 'FDB');
Insert into IPT_BASIC_COLOR_C
   (ID, REV_NBR, DESCRIPTION, DO_NOT_USE_IND, CHANGE_TYPE, CHANGE_USER_ID, CHANGE_TIMESTAMP, CONCEPT_REV_NBR, DCR_NBR, LEGACY_CHANGE_USER)
 Values
   (4, 1, 'clear', '0', 'A', 1, TIMESTAMP '2002-12-14 15:56:32', 1, 21666, 'FDB');
Insert into IPT_BASIC_COLOR_C
   (ID, REV_NBR, DESCRIPTION, DO_NOT_USE_IND, CHANGE_TYPE, CHANGE_USER_ID, CHANGE_TIMESTAMP, CONCEPT_REV_NBR, DCR_NBR, LEGACY_CHANGE_USER)
 Values
   (3, 1, 'brown', '0', 'A', 1, TIMESTAMP '2002-12-14 15:56:32', 1, 21666, 'FDB');
Insert into IPT_BASIC_COLOR_C
   (ID, REV_NBR, DESCRIPTION, DO_NOT_USE_IND, CHANGE_TYPE, CHANGE_USER_ID, CHANGE_TIMESTAMP, CONCEPT_REV_NBR, DCR_NBR, LEGACY_CHANGE_USER)
 Values
   (1, 2, 'black', '0', 'D', 1, TIMESTAMP '2002-12-14 17:34:39', 3, 21666, 'FDB');
Insert into IPT_BASIC_COLOR_C
   (ID, REV_NBR, DESCRIPTION, DO_NOT_USE_IND, CHANGE_TYPE, CHANGE_USER_ID, CHANGE_TIMESTAMP, CONCEPT_REV_NBR, DCR_NBR, LEGACY_CHANGE_USER)
 Values
   (19, 2, 'yellow', '0', 'D', 1, TIMESTAMP '2002-12-14 17:34:39', 3, 21666, 'FDB');
Insert into IPT_BASIC_COLOR_C
   (ID, REV_NBR, DESCRIPTION, DO_NOT_USE_IND, CHANGE_TYPE, CHANGE_USER_ID, CHANGE_TIMESTAMP, CONCEPT_REV_NBR, DCR_NBR, LEGACY_CHANGE_USER)
 Values
   (17, 2, 'turquoise', '0', 'D', 1, TIMESTAMP '2002-12-14 17:34:39', 3, 21666, 'FDB');
Insert into IPT_BASIC_COLOR_C
   (ID, REV_NBR, DESCRIPTION, DO_NOT_USE_IND, CHANGE_TYPE, CHANGE_USER_ID, CHANGE_TIMESTAMP, CONCEPT_REV_NBR, DCR_NBR, LEGACY_CHANGE_USER)
 Values
   (16, 2, 'tan', '0', 'D', 1, TIMESTAMP '2002-12-14 17:34:39', 3, 21666, 'FDB');
Insert into IPT_BASIC_COLOR_C
   (ID, REV_NBR, DESCRIPTION, DO_NOT_USE_IND, CHANGE_TYPE, CHANGE_USER_ID, CHANGE_TIMESTAMP, CONCEPT_REV_NBR, DCR_NBR, LEGACY_CHANGE_USER)
 Values
   (15, 2, 'red', '0', 'D', 1, TIMESTAMP '2002-12-14 17:34:39', 3, 21666, 'FDB');
Insert into IPT_BASIC_COLOR_C
   (ID, REV_NBR, DESCRIPTION, DO_NOT_USE_IND, CHANGE_TYPE, CHANGE_USER_ID, CHANGE_TIMESTAMP, CONCEPT_REV_NBR, DCR_NBR, LEGACY_CHANGE_USER)
 Values
   (14, 2, 'purple', '0', 'D', 1, TIMESTAMP '2002-12-14 17:34:39', 3, 21666, 'FDB');
Insert into IPT_BASIC_COLOR_C
   (ID, REV_NBR, DESCRIPTION, DO_NOT_USE_IND, CHANGE_TYPE, CHANGE_USER_ID, CHANGE_TIMESTAMP, CONCEPT_REV_NBR, DCR_NBR, LEGACY_CHANGE_USER)
 Values
   (13, 2, 'pink', '0', 'D', 1, TIMESTAMP '2002-12-14 17:34:39', 3, 21666, 'FDB');
Insert into IPT_BASIC_COLOR_C
   (ID, REV_NBR, DESCRIPTION, DO_NOT_USE_IND, CHANGE_TYPE, CHANGE_USER_ID, CHANGE_TIMESTAMP, CONCEPT_REV_NBR, DCR_NBR, LEGACY_CHANGE_USER)
 Values
   (12, 2, 'peach', '0', 'D', 1, TIMESTAMP '2002-12-14 17:34:39', 3, 21666, 'FDB');
Insert into IPT_BASIC_COLOR_C
   (ID, REV_NBR, DESCRIPTION, DO_NOT_USE_IND, CHANGE_TYPE, CHANGE_USER_ID, CHANGE_TIMESTAMP, CONCEPT_REV_NBR, DCR_NBR, LEGACY_CHANGE_USER)
 Values
   (11, 2, 'orange', '0', 'D', 1, TIMESTAMP '2002-12-14 17:34:39', 3, 21666, 'FDB');
Insert into IPT_BASIC_COLOR_C
   (ID, REV_NBR, DESCRIPTION, DO_NOT_USE_IND, CHANGE_TYPE, CHANGE_USER_ID, CHANGE_TIMESTAMP, CONCEPT_REV_NBR, DCR_NBR, LEGACY_CHANGE_USER)
 Values
   (10, 2, 'off-white', '0', 'D', 1, TIMESTAMP '2002-12-14 17:34:39', 3, 21666, 'FDB');
Insert into IPT_BASIC_COLOR_C
   (ID, REV_NBR, DESCRIPTION, DO_NOT_USE_IND, CHANGE_TYPE, CHANGE_USER_ID, CHANGE_TIMESTAMP, CONCEPT_REV_NBR, DCR_NBR, LEGACY_CHANGE_USER)
 Values
   (9, 2, 'multi-colored', '0', 'D', 1, TIMESTAMP '2002-12-14 17:34:39', 3, 21666, 'FDB');
Insert into IPT_BASIC_COLOR_C
   (ID, REV_NBR, DESCRIPTION, DO_NOT_USE_IND, CHANGE_TYPE, CHANGE_USER_ID, CHANGE_TIMESTAMP, CONCEPT_REV_NBR, DCR_NBR, LEGACY_CHANGE_USER)
 Values
   (8, 2, 'lavender', '0', 'D', 1, TIMESTAMP '2002-12-14 17:34:39', 3, 21666, 'FDB');
Insert into IPT_BASIC_COLOR_C
   (ID, REV_NBR, DESCRIPTION, DO_NOT_USE_IND, CHANGE_TYPE, CHANGE_USER_ID, CHANGE_TIMESTAMP, CONCEPT_REV_NBR, DCR_NBR, LEGACY_CHANGE_USER)
 Values
   (7, 2, 'green', '0', 'D', 1, TIMESTAMP '2002-12-14 17:34:39', 3, 21666, 'FDB');
Insert into IPT_BASIC_COLOR_C
   (ID, REV_NBR, DESCRIPTION, DO_NOT_USE_IND, CHANGE_TYPE, CHANGE_USER_ID, CHANGE_TIMESTAMP, CONCEPT_REV_NBR, DCR_NBR, LEGACY_CHANGE_USER)
 Values
   (6, 2, 'gray', '0', 'D', 1, TIMESTAMP '2002-12-14 17:34:39', 3, 21666, 'FDB');
Insert into IPT_BASIC_COLOR_C
   (ID, REV_NBR, DESCRIPTION, DO_NOT_USE_IND, CHANGE_TYPE, CHANGE_USER_ID, CHANGE_TIMESTAMP, CONCEPT_REV_NBR, DCR_NBR, LEGACY_CHANGE_USER)
 Values
   (5, 2, 'gold', '0', 'D', 1, TIMESTAMP '2002-12-14 17:34:39', 3, 21666, 'FDB');
Insert into IPT_BASIC_COLOR_C
   (ID, REV_NBR, DESCRIPTION, DO_NOT_USE_IND, CHANGE_TYPE, CHANGE_USER_ID, CHANGE_TIMESTAMP, CONCEPT_REV_NBR, DCR_NBR, LEGACY_CHANGE_USER)
 Values
   (4, 2, 'clear', '0', 'D', 1, TIMESTAMP '2002-12-14 17:34:39', 3, 21666, 'FDB');
Insert into IPT_BASIC_COLOR_C
   (ID, REV_NBR, DESCRIPTION, DO_NOT_USE_IND, CHANGE_TYPE, CHANGE_USER_ID, CHANGE_TIMESTAMP, CONCEPT_REV_NBR, DCR_NBR, LEGACY_CHANGE_USER)
 Values
   (3, 2, 'brown', '0', 'D', 1, TIMESTAMP '2002-12-14 17:34:39', 3, 21666, 'FDB');
Insert into IPT_BASIC_COLOR_C
   (ID, REV_NBR, DESCRIPTION, DO_NOT_USE_IND, CHANGE_TYPE, CHANGE_USER_ID, CHANGE_TIMESTAMP, CONCEPT_REV_NBR, DCR_NBR, LEGACY_CHANGE_USER)
 Values
   (2, 2, 'blue', '0', 'D', 1, TIMESTAMP '2002-12-14 17:34:39', 3, 21666, 'FDB');
Insert into IPT_BASIC_COLOR_C
   (ID, REV_NBR, DESCRIPTION, DO_NOT_USE_IND, CHANGE_TYPE, CHANGE_USER_ID, CHANGE_TIMESTAMP, CONCEPT_REV_NBR, DCR_NBR, LEGACY_CHANGE_USER)
 Values
   (18, 2, 'white', '0', 'D', 1, TIMESTAMP '2002-12-14 17:34:39', 3, 21666, 'FDB');
Insert into IPT_BASIC_COLOR_C
   (ID, REV_NBR, DESCRIPTION, DO_NOT_USE_IND, CHANGE_TYPE, CHANGE_USER_ID, CHANGE_TIMESTAMP, CONCEPT_REV_NBR, DCR_NBR, LEGACY_CHANGE_USER)
 Values
   (1, 3, 'black', '0', 'A', 1, TIMESTAMP '2002-12-14 17:34:42', 4, 21666, 'FDB');
Insert into IPT_BASIC_COLOR_C
   (ID, REV_NBR, DESCRIPTION, DO_NOT_USE_IND, CHANGE_TYPE, CHANGE_USER_ID, CHANGE_TIMESTAMP, CONCEPT_REV_NBR, DCR_NBR, LEGACY_CHANGE_USER)
 Values
   (2, 3, 'blue', '0', 'A', 1, TIMESTAMP '2002-12-14 17:34:42', 4, 21666, 'FDB');
Insert into IPT_BASIC_COLOR_C
   (ID, REV_NBR, DESCRIPTION, DO_NOT_USE_IND, CHANGE_TYPE, CHANGE_USER_ID, CHANGE_TIMESTAMP, CONCEPT_REV_NBR, DCR_NBR, LEGACY_CHANGE_USER)
 Values
   (3, 3, 'brown', '0', 'A', 1, TIMESTAMP '2002-12-14 17:34:42', 4, 21666, 'FDB');
Insert into IPT_BASIC_COLOR_C
   (ID, REV_NBR, DESCRIPTION, DO_NOT_USE_IND, CHANGE_TYPE, CHANGE_USER_ID, CHANGE_TIMESTAMP, CONCEPT_REV_NBR, DCR_NBR, LEGACY_CHANGE_USER)
 Values
   (4, 3, 'clear', '0', 'A', 1, TIMESTAMP '2002-12-14 17:34:42', 4, 21666, 'FDB');
Insert into IPT_BASIC_COLOR_C
   (ID, REV_NBR, DESCRIPTION, DO_NOT_USE_IND, CHANGE_TYPE, CHANGE_USER_ID, CHANGE_TIMESTAMP, CONCEPT_REV_NBR, DCR_NBR, LEGACY_CHANGE_USER)
 Values
   (5, 3, 'gold', '0', 'A', 1, TIMESTAMP '2002-12-14 17:34:42', 4, 21666, 'FDB');
Insert into IPT_BASIC_COLOR_C
   (ID, REV_NBR, DESCRIPTION, DO_NOT_USE_IND, CHANGE_TYPE, CHANGE_USER_ID, CHANGE_TIMESTAMP, CONCEPT_REV_NBR, DCR_NBR, LEGACY_CHANGE_USER)
 Values
   (6, 3, 'gray', '0', 'A', 1, TIMESTAMP '2002-12-14 17:34:42', 4, 21666, 'FDB');
Insert into IPT_BASIC_COLOR_C
   (ID, REV_NBR, DESCRIPTION, DO_NOT_USE_IND, CHANGE_TYPE, CHANGE_USER_ID, CHANGE_TIMESTAMP, CONCEPT_REV_NBR, DCR_NBR, LEGACY_CHANGE_USER)
 Values
   (7, 3, 'green', '0', 'A', 1, TIMESTAMP '2002-12-14 17:34:42', 4, 21666, 'FDB');
Insert into IPT_BASIC_COLOR_C
   (ID, REV_NBR, DESCRIPTION, DO_NOT_USE_IND, CHANGE_TYPE, CHANGE_USER_ID, CHANGE_TIMESTAMP, CONCEPT_REV_NBR, DCR_NBR, LEGACY_CHANGE_USER)
 Values
   (8, 3, 'lavender', '0', 'A', 1, TIMESTAMP '2002-12-14 17:34:42', 4, 21666, 'FDB');
Insert into IPT_BASIC_COLOR_C
   (ID, REV_NBR, DESCRIPTION, DO_NOT_USE_IND, CHANGE_TYPE, CHANGE_USER_ID, CHANGE_TIMESTAMP, CONCEPT_REV_NBR, DCR_NBR, LEGACY_CHANGE_USER)
 Values
   (9, 3, 'multi-colored', '0', 'A', 1, TIMESTAMP '2002-12-14 17:34:42', 4, 21666, 'FDB');
Insert into IPT_BASIC_COLOR_C
   (ID, REV_NBR, DESCRIPTION, DO_NOT_USE_IND, CHANGE_TYPE, CHANGE_USER_ID, CHANGE_TIMESTAMP, CONCEPT_REV_NBR, DCR_NBR, LEGACY_CHANGE_USER)
 Values
   (10, 3, 'off-white', '0', 'A', 1, TIMESTAMP '2002-12-14 17:34:42', 4, 21666, 'FDB');
Insert into IPT_BASIC_COLOR_C
   (ID, REV_NBR, DESCRIPTION, DO_NOT_USE_IND, CHANGE_TYPE, CHANGE_USER_ID, CHANGE_TIMESTAMP, CONCEPT_REV_NBR, DCR_NBR, LEGACY_CHANGE_USER)
 Values
   (11, 3, 'orange', '0', 'A', 1, TIMESTAMP '2002-12-14 17:34:42', 4, 21666, 'FDB');
Insert into IPT_BASIC_COLOR_C
   (ID, REV_NBR, DESCRIPTION, DO_NOT_USE_IND, CHANGE_TYPE, CHANGE_USER_ID, CHANGE_TIMESTAMP, CONCEPT_REV_NBR, DCR_NBR, LEGACY_CHANGE_USER)
 Values
   (12, 3, 'peach', '0', 'A', 1, TIMESTAMP '2002-12-14 17:34:42', 4, 21666, 'FDB');
Insert into IPT_BASIC_COLOR_C
   (ID, REV_NBR, DESCRIPTION, DO_NOT_USE_IND, CHANGE_TYPE, CHANGE_USER_ID, CHANGE_TIMESTAMP, CONCEPT_REV_NBR, DCR_NBR, LEGACY_CHANGE_USER)
 Values
   (13, 3, 'pink', '0', 'A', 1, TIMESTAMP '2002-12-14 17:34:42', 4, 21666, 'FDB');
Insert into IPT_BASIC_COLOR_C
   (ID, REV_NBR, DESCRIPTION, DO_NOT_USE_IND, CHANGE_TYPE, CHANGE_USER_ID, CHANGE_TIMESTAMP, CONCEPT_REV_NBR, DCR_NBR, LEGACY_CHANGE_USER)
 Values
   (14, 3, 'purple', '0', 'A', 1, TIMESTAMP '2002-12-14 17:34:42', 4, 21666, 'FDB');
Insert into IPT_BASIC_COLOR_C
   (ID, REV_NBR, DESCRIPTION, DO_NOT_USE_IND, CHANGE_TYPE, CHANGE_USER_ID, CHANGE_TIMESTAMP, CONCEPT_REV_NBR, DCR_NBR, LEGACY_CHANGE_USER)
 Values
   (15, 3, 'red', '0', 'A', 1, TIMESTAMP '2002-12-14 17:34:42', 4, 21666, 'FDB');
Insert into IPT_BASIC_COLOR_C
   (ID, REV_NBR, DESCRIPTION, DO_NOT_USE_IND, CHANGE_TYPE, CHANGE_USER_ID, CHANGE_TIMESTAMP, CONCEPT_REV_NBR, DCR_NBR, LEGACY_CHANGE_USER)
 Values
   (16, 3, 'tan', '0', 'A', 1, TIMESTAMP '2002-12-14 17:34:42', 4, 21666, 'FDB');
Insert into IPT_BASIC_COLOR_C
   (ID, REV_NBR, DESCRIPTION, DO_NOT_USE_IND, CHANGE_TYPE, CHANGE_USER_ID, CHANGE_TIMESTAMP, CONCEPT_REV_NBR, DCR_NBR, LEGACY_CHANGE_USER)
 Values
   (17, 3, 'turquoise', '0', 'A', 1, TIMESTAMP '2002-12-14 17:34:42', 4, 21666, 'FDB');
Insert into IPT_BASIC_COLOR_C
   (ID, REV_NBR, DESCRIPTION, DO_NOT_USE_IND, CHANGE_TYPE, CHANGE_USER_ID, CHANGE_TIMESTAMP, CONCEPT_REV_NBR, DCR_NBR, LEGACY_CHANGE_USER)
 Values
   (18, 3, 'white', '0', 'A', 1, TIMESTAMP '2002-12-14 17:34:42', 4, 21666, 'FDB');
Insert into IPT_BASIC_COLOR_C
   (ID, REV_NBR, DESCRIPTION, DO_NOT_USE_IND, CHANGE_TYPE, CHANGE_USER_ID, CHANGE_TIMESTAMP, CONCEPT_REV_NBR, DCR_NBR, LEGACY_CHANGE_USER)
 Values
   (19, 3, 'yellow', '0', 'A', 1, TIMESTAMP '2002-12-14 17:34:42', 4, 21666, 'FDB');
Insert into IPT_BASIC_COLOR_C
   (ID, REV_NBR, DESCRIPTION, ABBREVIATION, SHORT_ABBREVIATION, DO_NOT_USE_IND, CHANGE_TYPE, CHANGE_USER_ID, CHANGE_TIMESTAMP, CONCEPT_REV_NBR, DCR_NBR, LEGACY_CHANGE_USER)
 Values
   (1, 4, 'black', 'black', 'blck', '0', 'C', 1, TIMESTAMP '2009-06-15 14:56:34', 6, 6953, 'DCR6953');
Insert into IPT_BASIC_COLOR_C
   (ID, REV_NBR, DESCRIPTION, ABBREVIATION, SHORT_ABBREVIATION, DO_NOT_USE_IND, CHANGE_TYPE, CHANGE_USER_ID, CHANGE_TIMESTAMP, CONCEPT_REV_NBR, DCR_NBR, LEGACY_CHANGE_USER)
 Values
   (19, 4, 'yellow', 'yellow', 'yell', '0', 'C', 1, TIMESTAMP '2009-06-15 14:56:34', 6, 6953, 'DCR6953');
Insert into IPT_BASIC_COLOR_C
   (ID, REV_NBR, DESCRIPTION, ABBREVIATION, SHORT_ABBREVIATION, DO_NOT_USE_IND, CHANGE_TYPE, CHANGE_USER_ID, CHANGE_TIMESTAMP, CONCEPT_REV_NBR, DCR_NBR, LEGACY_CHANGE_USER)
 Values
   (3, 4, 'brown', 'brown', 'brwn', '0', 'C', 1, TIMESTAMP '2009-06-15 14:56:34', 6, 6953, 'DCR6953');
Insert into IPT_BASIC_COLOR_C
   (ID, REV_NBR, DESCRIPTION, ABBREVIATION, SHORT_ABBREVIATION, DO_NOT_USE_IND, CHANGE_TYPE, CHANGE_USER_ID, CHANGE_TIMESTAMP, CONCEPT_REV_NBR, DCR_NBR, LEGACY_CHANGE_USER)
 Values
   (4, 4, 'clear', 'clear', 'clr', '0', 'C', 1, TIMESTAMP '2009-06-15 14:56:34', 6, 6953, 'DCR6953');
Insert into IPT_BASIC_COLOR_C
   (ID, REV_NBR, DESCRIPTION, ABBREVIATION, SHORT_ABBREVIATION, DO_NOT_USE_IND, CHANGE_TYPE, CHANGE_USER_ID, CHANGE_TIMESTAMP, CONCEPT_REV_NBR, DCR_NBR, LEGACY_CHANGE_USER)
 Values
   (5, 4, 'gold', 'gold', 'gold', '0', 'C', 1, TIMESTAMP '2009-06-15 14:56:34', 6, 6953, 'DCR6953');
Insert into IPT_BASIC_COLOR_C
   (ID, REV_NBR, DESCRIPTION, ABBREVIATION, SHORT_ABBREVIATION, DO_NOT_USE_IND, CHANGE_TYPE, CHANGE_USER_ID, CHANGE_TIMESTAMP, CONCEPT_REV_NBR, DCR_NBR, LEGACY_CHANGE_USER)
 Values
   (6, 4, 'gray', 'gray', 'gray', '0', 'C', 1, TIMESTAMP '2009-06-15 14:56:34', 6, 6953, 'DCR6953');
Insert into IPT_BASIC_COLOR_C
   (ID, REV_NBR, DESCRIPTION, ABBREVIATION, SHORT_ABBREVIATION, DO_NOT_USE_IND, CHANGE_TYPE, CHANGE_USER_ID, CHANGE_TIMESTAMP, CONCEPT_REV_NBR, DCR_NBR, LEGACY_CHANGE_USER)
 Values
   (7, 4, 'green', 'green', 'grn', '0', 'C', 1, TIMESTAMP '2009-06-15 14:56:34', 6, 6953, 'DCR6953');
Insert into IPT_BASIC_COLOR_C
   (ID, REV_NBR, DESCRIPTION, ABBREVIATION, SHORT_ABBREVIATION, DO_NOT_USE_IND, CHANGE_TYPE, CHANGE_USER_ID, CHANGE_TIMESTAMP, CONCEPT_REV_NBR, DCR_NBR, LEGACY_CHANGE_USER)
 Values
   (8, 4, 'lavender', 'lavndr', 'lvdr', '0', 'C', 1, TIMESTAMP '2009-06-15 14:56:34', 6, 6953, 'DCR6953');
Insert into IPT_BASIC_COLOR_C
   (ID, REV_NBR, DESCRIPTION, ABBREVIATION, SHORT_ABBREVIATION, DO_NOT_USE_IND, CHANGE_TYPE, CHANGE_USER_ID, CHANGE_TIMESTAMP, CONCEPT_REV_NBR, DCR_NBR, LEGACY_CHANGE_USER)
 Values
   (9, 4, 'multi-colored', 'mlt-clr', 'mult', '0', 'C', 1, TIMESTAMP '2009-06-15 14:56:34', 6, 6953, 'DCR6953');
Insert into IPT_BASIC_COLOR_C
   (ID, REV_NBR, DESCRIPTION, ABBREVIATION, SHORT_ABBREVIATION, DO_NOT_USE_IND, CHANGE_TYPE, CHANGE_USER_ID, CHANGE_TIMESTAMP, CONCEPT_REV_NBR, DCR_NBR, LEGACY_CHANGE_USER)
 Values
   (10, 4, 'off-white', 'off-wht', 'wht', '0', 'C', 1, TIMESTAMP '2009-06-15 14:56:34', 6, 6953, 'DCR6953');
Insert into IPT_BASIC_COLOR_C
   (ID, REV_NBR, DESCRIPTION, ABBREVIATION, SHORT_ABBREVIATION, DO_NOT_USE_IND, CHANGE_TYPE, CHANGE_USER_ID, CHANGE_TIMESTAMP, CONCEPT_REV_NBR, DCR_NBR, LEGACY_CHANGE_USER)
 Values
   (11, 4, 'orange', 'orange', 'orng', '0', 'C', 1, TIMESTAMP '2009-06-15 14:56:34', 6, 6953, 'DCR6953');
Insert into IPT_BASIC_COLOR_C
   (ID, REV_NBR, DESCRIPTION, ABBREVIATION, SHORT_ABBREVIATION, DO_NOT_USE_IND, CHANGE_TYPE, CHANGE_USER_ID, CHANGE_TIMESTAMP, CONCEPT_REV_NBR, DCR_NBR, LEGACY_CHANGE_USER)
 Values
   (12, 4, 'peach', 'peach', 'pch', '0', 'C', 1, TIMESTAMP '2009-06-15 14:56:34', 6, 6953, 'DCR6953');
Insert into IPT_BASIC_COLOR_C
   (ID, REV_NBR, DESCRIPTION, ABBREVIATION, SHORT_ABBREVIATION, DO_NOT_USE_IND, CHANGE_TYPE, CHANGE_USER_ID, CHANGE_TIMESTAMP, CONCEPT_REV_NBR, DCR_NBR, LEGACY_CHANGE_USER)
 Values
   (13, 4, 'pink', 'pink', 'pink', '0', 'C', 1, TIMESTAMP '2009-06-15 14:56:34', 6, 6953, 'DCR6953');
Insert into IPT_BASIC_COLOR_C
   (ID, REV_NBR, DESCRIPTION, ABBREVIATION, SHORT_ABBREVIATION, DO_NOT_USE_IND, CHANGE_TYPE, CHANGE_USER_ID, CHANGE_TIMESTAMP, CONCEPT_REV_NBR, DCR_NBR, LEGACY_CHANGE_USER)
 Values
   (14, 4, 'purple', 'purple', 'prpl', '0', 'C', 1, TIMESTAMP '2009-06-15 14:56:34', 6, 6953, 'DCR6953');
Insert into IPT_BASIC_COLOR_C
   (ID, REV_NBR, DESCRIPTION, ABBREVIATION, SHORT_ABBREVIATION, DO_NOT_USE_IND, CHANGE_TYPE, CHANGE_USER_ID, CHANGE_TIMESTAMP, CONCEPT_REV_NBR, DCR_NBR, LEGACY_CHANGE_USER)
 Values
   (15, 4, 'red', 'red', 'red', '0', 'C', 1, TIMESTAMP '2009-06-15 14:56:34', 6, 6953, 'DCR6953');
Insert into IPT_BASIC_COLOR_C
   (ID, REV_NBR, DESCRIPTION, ABBREVIATION, SHORT_ABBREVIATION, DO_NOT_USE_IND, CHANGE_TYPE, CHANGE_USER_ID, CHANGE_TIMESTAMP, CONCEPT_REV_NBR, DCR_NBR, LEGACY_CHANGE_USER)
 Values
   (16, 4, 'tan', 'tan', 'tan', '0', 'C', 1, TIMESTAMP '2009-06-15 14:56:34', 6, 6953, 'DCR6953');
Insert into IPT_BASIC_COLOR_C
   (ID, REV_NBR, DESCRIPTION, ABBREVIATION, SHORT_ABBREVIATION, DO_NOT_USE_IND, CHANGE_TYPE, CHANGE_USER_ID, CHANGE_TIMESTAMP, CONCEPT_REV_NBR, DCR_NBR, LEGACY_CHANGE_USER)
 Values
   (17, 4, 'turquoise', 'turquos', 'turq', '0', 'C', 1, TIMESTAMP '2009-06-15 14:56:34', 6, 6953, 'DCR6953');
Insert into IPT_BASIC_COLOR_C
   (ID, REV_NBR, DESCRIPTION, ABBREVIATION, SHORT_ABBREVIATION, DO_NOT_USE_IND, CHANGE_TYPE, CHANGE_USER_ID, CHANGE_TIMESTAMP, CONCEPT_REV_NBR, DCR_NBR, LEGACY_CHANGE_USER)
 Values
   (18, 4, 'white', 'white', 'wht', '0', 'C', 1, TIMESTAMP '2009-06-15 14:56:34', 6, 6953, 'DCR6953');
Insert into IPT_BASIC_COLOR_C
   (ID, REV_NBR, DESCRIPTION, ABBREVIATION, SHORT_ABBREVIATION, DO_NOT_USE_IND, CHANGE_TYPE, CHANGE_USER_ID, CHANGE_TIMESTAMP, CONCEPT_REV_NBR, DCR_NBR, LEGACY_CHANGE_USER)
 Values
   (2, 4, 'blue', 'blue', 'blue', '0', 'C', 1, TIMESTAMP '2009-06-15 14:56:34', 6, 6953, 'DCR6953');
Insert into IPT_BASIC_COLOR_C
   (ID, REV_NBR, DESCRIPTION, ABBREVIATION, SHORT_ABBREVIATION, DO_NOT_USE_IND, CHANGE_TYPE, CHANGE_USER_ID, CHANGE_TIMESTAMP, CONCEPT_REV_NBR, DCR_NBR)
 Values
   (10, 5, 'off-white', 'off-wht', 'owht', '0', 'C', 1, TIMESTAMP '2021-04-16 13:31:20', 8, 21666);
